# ${project.name} Config

# Version
version: "1.0"

# Settings
settings:

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What language should be used when sending messages?
  language: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Timeout Settings
  timeout:

    # How long should a player be able to idle when adding a new message? (In Seconds)
    messageAddition: 60

    # How long should a player be able to idle when listing messages? (In Seconds)
    messageListing: 60

    # How long should a player be able to idle when removing a message? (In Seconds)
    messageRemoval: 60

    # How long should a player be able to idle when distributing a message? (In Seconds)
    messageDistribute: 60

  # Broadcast settings
  broadcast:

    # Should messages be prefixed?
    prefixEnabled: true

    # What prefix should be used before messages?
    prefix: "&f[&r&2Broadcast&r&f]&r "

    # How many players are required for broadcasts to send?
    requiredPlayers: 1

    # Should message counters ignore player counts and keep counting up when there are not enough players on?
    counterIgnoresPlayerCount: false
