# TimedBroadcast Config

# Version
version: 1.0

# Settings
settings:

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What language should be used when sending messages?
  language: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Updater Settings
  updater:

    # Is the updater enabled?
    enabled: true

    # What modes should be used when updating? | notify - notifies console and people with permission of new updates | update - downloads new updates then notifies console and people with relevent permissions
    mode: notify

    # Should the download information of updates be logged to console?
    log-downloads: false

  # What prefix should be used for the messenger?
  messenger-prefix: "&f[&r&2Broadcast&r&f]&r"

  # Should messages be prefixed?
  prefix-messages: true

  # Should the progress of displaying messages be saved and resumed when the server is restarted?
  resume-on-restart: true

  # Should the state of broadcasting be saved between restarts? (Will stay off if they were off or on if they were on)
  save-state: true

  # Message Settings
  messages:

    # Settings for the first message
    message1:

      # Is the message enabled?
      enabled: true

      # What is the message to broadcast? (Allows formatting codes)
      message-text: "&2Message with a 2 minute interval"

      # What time unit should be used for the message? (minute, second)
      time-unit: minute

      # How long should the message wait between broadcasts?
      time-interval: 2

    # Settings for the seconds message
    message2:

      # Is the message enabled?
      enabled: true

      # What is the message to broadcast? (Allows formatting codes)
      message-text: "&7Message with a 20 second interval"

      # What time unit should be used for the message? (minute, second)
      time-unit: second

      # How long should the message wait between broadcasts?
      time-interval: 20

