# ${project.name} Config

# Version
version: "1.0"

# Settings
settings:

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What language should be used when sending messages?
  language: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Timeout Settings
  timeout:

    # How long should a player be able to idle when adding a new message? (In Seconds)
    messageAddition: 30
