name: ${project.name}
version: ${project.version}
authors: [${project.authors}]
description: ${project.description}

depend: ${project.depends}
main: ${project.main}

commands:
  ${project.name}:
    description: master command system for the ${project.name}
    usage: "${project.name} Usage: /${project.name.lowercase} help"
    aliases: [${project.name.short}]
  broadcast:
    description: master command for message management
    aliases: [broad]
permissions:

  # Singular Nodes
  ${project.name.lowercase}.commands.reload:
    description: "Allows use of the reload subcommand"
    default: op

  ${project.name.lowercase}.commands.add:
    description: "Allows use of the add subcommand of the broadcast command"
    default: op

  ${project.name.lowercase}.commands.list:
    description: "Allows use of the list subcommand of the broadcast command"
    default: op

  ${project.name.lowercase}.commands.remove:
    description: "Allows use of the remove subcommand of the broadcast command"
    default: op

  ${project.name.lowercase}.commands.stop:
    description: "Allows use of the stop subcommand of the broadcast command"
    default: op

  ${project.name.lowercase}.commands.start:
    description: "Allows use of the start subcommand of the broadcast command"
    default: op

  ${project.name.lowercase}.commands.distribute:
    description: "Allows use of the distribute subcommand of the broadcast command"
    default: op
