name: ${project.name}
version: ${project.version}
author: ${project.author}
description: ${project.description}

depend: ${project.depends}
main: ${project.main}

commands:
  ${project.name}:
    description: master command system for the ${project.name}
    usage: "${project.name} Usage: /${project.name.lowercase} help"
    aliases: [${project.name.short}]
permissions:

  # Singular Nodes
  ${project.name}.commands.reload:
    description: "Allows use of the reload subcommand"
    default: op
